## Import Libraries

In [ ]:
import pandas as pd
import requests

## Connect to google drive folder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Read the Flights CSV file

In [ ]:
flights_path = '/content/drive/MyDrive/Data Science Group Project/Notebooks/data/kaggle_dataset/flights.csv'

In [ ]:
flights_df = pd.read_csv(flights_path)

/tmp/ipython-input-78065572.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  flights_df = pd.read_csv(flights_path)

## Make a dataframe of the first 20 rows for testing

In [ ]:
flights_df_20 = flights_df.head(20)
flights_df_20

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,1,1,4,DL,806,N3730B,SFO,MSP,25,...,610.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,1,1,4,NK,612,N635NK,LAS,MSP,25,...,509.0,-17.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,1,1,4,US,2013,N584UW,LAX,CLT,30,...,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,...,532.0,-13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,1,1,4,DL,1173,N826DN,LAS,ATL,30,...,656.0,-15.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,2015,1,1,4,DL,2336,N958DN,DEN,ATL,30,...,453.0,-30.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
11,2015,1,1,4,AA,1674,N853AA,LAS,MIA,35,...,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
12,2015,1,1,4,DL,1434,N547US,LAX,MSP,35,...,605.0,-4.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
13,2015,1,1,4,DL,2324,N3751B,SLC,ATL,40,...,553.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
14,2015,1,1,4,DL,2440,N651DL,SEA,MSP,40,...,557.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,2015,1,1,4,AS,108,N309AS,ANC,SEA,45,...,455.0,-14.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
16,2015,1,1,4,DL,1560,N3743H,ANC,SEA,45,...,451.0,-24.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
17,2015,1,1,4,UA,1197,N78448,SFO,IAH,48,...,619.0,-7.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,2015,1,1,4,AS,122,N413AS,ANC,PDX,50,...,507.0,-18.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
19,2015,1,1,4,DL,1670,N806DN,PDX,MSP,50,...,551.0,-12.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

## Read the airports file

In [ ]:
airports_path = '/content/drive/MyDrive/Data Science Group Project/Notebooks/data/kaggle_dataset/airports.csv'

In [ ]:
airports_df = pd.read_csv(airports_path)

## Merge the flights and airports dataframes based on the origin airport and IATA code

In [ ]:
flights_df_merged = flights_df_20.merge(airports_df, left_on='ORIGIN_AIRPORT', right_on='IATA_CODE', how='left')
flights_df_merged

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,NaN,NaN,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,NaN,NaN,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,NaN,NaN,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,NaN,NaN,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,NaN,NaN,NaN,SEA,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931
5,2015,1,1,4,DL,806,N3730B,SFO,MSP,25,...,NaN,NaN,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484
6,2015,1,1,4,NK,612,N635NK,LAS,MSP,25,...,NaN,NaN,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233
7,2015,1,1,4,US,2013,N584UW,LAX,CLT,30,...,NaN,NaN,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,...,NaN,NaN,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484
9,2015,1,1,4,DL,1173,N826DN,LAS,ATL,30,...,NaN,NaN,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233
10,2015,1,1,4,DL,2336,N958DN,DEN,ATL,30,...,NaN,NaN,NaN,DEN,Denver International Airport,Denver,CO,USA,39.85841,-104.66700
11,2015,1,1,4,AA,1674,N853AA,LAS,MIA,35,...,NaN,NaN,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233
12,2015,1,1,4,DL,1434,N547US,LAX,MSP,35,...,NaN,NaN,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
13,2015,1,1,4,DL,2324,N3751B,SLC,ATL,40,...,NaN,NaN,NaN,SLC,Salt Lake City International Airport,Salt Lake City,UT,USA,40.78839,-111.97777
14,2015,1,1,4,DL,2440,N651DL,SEA,MSP,40,...,NaN,NaN,NaN,SEA,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931
15,2015,1,1,4,AS,108,N309AS,ANC,SEA,45,...,NaN,NaN,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619
16,2015,1,1,4,DL,1560,N3743H,ANC,SEA,45,...,NaN,NaN,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619
17,2015,1,1,4,UA,1197,N78448,SFO,IAH,48,...,NaN,NaN,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484
18,2015,1,1,4,AS,122,N413AS,ANC,PDX,50,...,NaN,NaN,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619
19,2015,1,1,4,DL,1670,N806DN,PDX,MSP,50,...,NaN,NaN,NaN,PDX,Portland International Airport,Portland,OR,USA,45.58872,-122.59750

## Create a DATE column
#### This needs to be improved to get the date into the YYYY-MM-DD format

In [ ]:
flights_df_merged['DATE'] = flights_df_merged['YEAR'].map(str) + '-' + flights_df_merged['MONTH'].map(str) + '-' + flights_df_merged['DAY'].map(str)

In [ ]:
flights_df_merged

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE,DATE
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,NaN,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,2015-1-1
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,NaN,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,2015-1-1
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,NaN,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,2015-1-1
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,NaN,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,2015-1-1
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,NaN,NaN,SEA,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931,2015-1-1
5,2015,1,1,4,DL,806,N3730B,SFO,MSP,25,...,NaN,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,2015-1-1
6,2015,1,1,4,NK,612,N635NK,LAS,MSP,25,...,NaN,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233,2015-1-1
7,2015,1,1,4,US,2013,N584UW,LAX,CLT,30,...,NaN,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,2015-1-1
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,...,NaN,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,2015-1-1
9,2015,1,1,4,DL,1173,N826DN,LAS,ATL,30,...,NaN,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233,2015-1-1
10,2015,1,1,4,DL,2336,N958DN,DEN,ATL,30,...,NaN,NaN,DEN,Denver International Airport,Denver,CO,USA,39.85841,-104.66700,2015-1-1
11,2015,1,1,4,AA,1674,N853AA,LAS,MIA,35,...,NaN,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233,2015-1-1
12,2015,1,1,4,DL,1434,N547US,LAX,MSP,35,...,NaN,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,2015-1-1
13,2015,1,1,4,DL,2324,N3751B,SLC,ATL,40,...,NaN,NaN,SLC,Salt Lake City International Airport,Salt Lake City,UT,USA,40.78839,-111.97777,2015-1-1
14,2015,1,1,4,DL,2440,N651DL,SEA,MSP,40,...,NaN,NaN,SEA,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931,2015-1-1
15,2015,1,1,4,AS,108,N309AS,ANC,SEA,45,...,NaN,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,2015-1-1
16,2015,1,1,4,DL,1560,N3743H,ANC,SEA,45,...,NaN,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,2015-1-1
17,2015,1,1,4,UA,1197,N78448,SFO,IAH,48,...,NaN,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,2015-1-1
18,2015,1,1,4,AS,122,N413AS,ANC,PDX,50,...,NaN,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,2015-1-1
19,2015,1,1,4,DL,1670,N806DN,PDX,MSP,50,...,NaN,NaN,PDX,Portland International Airport,Portland,OR,USA,45.58872,-122.59750,2015-1-1

## Function for calling the Historical Weather API

In [ ]:
def get_weather_info(row):

  latitude = row['LATITUDE']
  longitude = row['LONGITUDE']
  start_date = '2015-01-01'
  end_date = '2015-01-01'

  endpoint = 'https://archive-api.open-meteo.com/v1/archive?latitude={}&longitude={}&start_date={}&end_date={}&daily=weather_code&timezone=auto'.format(latitude, longitude, start_date, end_date)

  response = requests.get(url=endpoint)
  data = response.json()
  weather_codes = data['daily']['weather_code']

  row['API_WEATHER_CODES'] = weather_codes
  return row

## Apply the API function row wise

In [ ]:
flights_df_merged = flights_df_merged.apply(get_weather_info, axis=1)

In [ ]:
flights_df_merged

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,WEATHER_DELAY,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE,DATE,API_WEATHER_CODES
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,2015-1-1,[71]
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,2015-1-1,[0]
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,2015-1-1,[0]
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,2015-1-1,[0]
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,NaN,SEA,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931,2015-1-1,[3]
5,2015,1,1,4,DL,806,N3730B,SFO,MSP,25,...,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,2015-1-1,[0]
6,2015,1,1,4,NK,612,N635NK,LAS,MSP,25,...,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233,2015-1-1,[3]
7,2015,1,1,4,US,2013,N584UW,LAX,CLT,30,...,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,2015-1-1,[0]
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,...,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,2015-1-1,[0]
9,2015,1,1,4,DL,1173,N826DN,LAS,ATL,30,...,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233,2015-1-1,[3]
10,2015,1,1,4,DL,2336,N958DN,DEN,ATL,30,...,NaN,DEN,Denver International Airport,Denver,CO,USA,39.85841,-104.66700,2015-1-1,[71]
11,2015,1,1,4,AA,1674,N853AA,LAS,MIA,35,...,NaN,LAS,McCarran International Airport,Las Vegas,NV,USA,36.08036,-115.15233,2015-1-1,[3]
12,2015,1,1,4,DL,1434,N547US,LAX,MSP,35,...,NaN,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,2015-1-1,[0]
13,2015,1,1,4,DL,2324,N3751B,SLC,ATL,40,...,NaN,SLC,Salt Lake City International Airport,Salt Lake City,UT,USA,40.78839,-111.97777,2015-1-1,[2]
14,2015,1,1,4,DL,2440,N651DL,SEA,MSP,40,...,NaN,SEA,Seattle-Tacoma International Airport,Seattle,WA,USA,47.44898,-122.30931,2015-1-1,[3]
15,2015,1,1,4,AS,108,N309AS,ANC,SEA,45,...,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,2015-1-1,[71]
16,2015,1,1,4,DL,1560,N3743H,ANC,SEA,45,...,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,2015-1-1,[71]
17,2015,1,1,4,UA,1197,N78448,SFO,IAH,48,...,NaN,SFO,San Francisco International Airport,San Francisco,CA,USA,37.61900,-122.37484,2015-1-1,[0]
18,2015,1,1,4,AS,122,N413AS,ANC,PDX,50,...,NaN,ANC,Ted Stevens Anchorage International Airport,Anchorage,AK,USA,61.17432,-149.99619,2015-1-1,[71]
19,2015,1,1,4,DL,1670,N806DN,PDX,MSP,50,...,NaN,PDX,Portland International Airport,Portland,OR,USA,45.58872,-122.59750,2015-1-1,[3]

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline